name: Deploy Monitoring Stack
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Docker Compose
        run: |
          docker compose down
          docker compose up -d
